name: Build
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.8
      - name: Fetch deps
        run: cd example && flutter pub get
      - name: Build APK
        run: cd example && flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: example/build/app/outputs/flutter-apk
